#!/usr/bin/env bash
set -euo pipefail

IAC_DIR="${1:-./iac/aws}"
OUTPUT_FILE="${2:-./.env.local}"

# Get required values from parameter or env var, fail if missing
get_required_value() {
  local param_name="$1"
  local env_var="$2"
  local field_name="$3"
  
  # Check if provided as parameter
  if [ -n "$param_name" ]; then
    echo "$param_name"
    return
  fi
  
  # Check environment variable
  if [ -n "${!env_var:-}" ]; then
    echo "${!env_var}"
    return
  fi
  
  # Fail - no value available
  echo "❌ Missing required configuration: $field_name" >&2
  echo "   Provide via parameter or $env_var environment variable" >&2
  exit 1
}

if [ ! -d "$IAC_DIR" ]; then
  echo "IaC directory not found: $IAC_DIR" >&2
  exit 1
fi

pushd "$IAC_DIR" >/dev/null
JSON=$(terraform output -json || true)
if [ -z "$JSON" ]; then
  echo "Terraform output is empty. Run 'terraform apply' first." >&2
  exit 1
fi

API_URL=$(echo "$JSON" | python -c "import json,sys; o=json.load(sys.stdin); print(o['api_webhook_url']['value'])")
BUCKET=$(echo "$JSON" | python -c "import json,sys; o=json.load(sys.stdin); print(o['s3_bucket_name']['value'])")
EVENTGRID_URI=$(echo "$JSON" | python -c "import json,sys; o=json.load(sys.stdin); print(o.get('eventgrid_topic_endpoint', {}).get('value', ''))" || true)
EVENTGRID_KEY=$(echo "$JSON" | python -c "import json,sys; o=json.load(sys.stdin); print(o.get('eventgrid_topic_key', {}).get('value', ''))" || true)

if [ -z "$API_URL" ] || [ -z "$BUCKET" ]; then
  echo "❌ Missing required Terraform outputs" >&2
  echo "   Ensure 'terraform apply' has been run and outputs include:" >&2
  echo "   - api_webhook_url" >&2
  echo "   - s3_bucket_name" >&2
  exit 1
fi

popd >/dev/null

# Validate required secrets
WEBHOOK_SECRET=$(get_required_value "${WEBHOOK_AUTH_SECRET:-}" "WEBHOOK_AUTH_SECRET" "WEBHOOK_AUTH_SECRET")
TENANT_ID=$(get_required_value "${GRAPH_TENANT_ID:-}" "GRAPH_TENANT_ID" "GRAPH_TENANT_ID")
CLIENT_ID=$(get_required_value "${GRAPH_CLIENT_ID:-}" "GRAPH_CLIENT_ID" "GRAPH_CLIENT_ID")
CLIENT_SECRET=$(get_required_value "${GRAPH_CLIENT_SECRET:-}" "GRAPH_CLIENT_SECRET" "GRAPH_CLIENT_SECRET")
GROUP_ID=$(get_required_value "${ENTRA_GROUP_ID:-}" "ENTRA_GROUP_ID" "ENTRA_GROUP_ID")

cat > "$OUTPUT_FILE" <<EOF
# Generated by scripts/config/generate-aws-env.sh
# Do not commit this file

AWS_WEBHOOK_ENDPOINT=$API_URL
AWS_S3_BUCKET=$BUCKET

# Required values (validated at generation time)
WEBHOOK_AUTH_SECRET=$WEBHOOK_SECRET
GRAPH_TENANT_ID=$TENANT_ID
GRAPH_CLIENT_ID=$CLIENT_ID
GRAPH_CLIENT_SECRET=$CLIENT_SECRET
ENTRA_GROUP_ID=$GROUP_ID

# Optional: Event Grid
EVENTGRID_URI=${EVENTGRID_URI:-}
EVENTGRID_KEY=${EVENTGRID_KEY:-}
EOF

echo ""
echo "✅ Generated: $OUTPUT_FILE"
echo "   All required values validated and present"
