#!/usr/bin/env bash
set -euo pipefail

IAC_DIR="${1:-./iac/azure}"
OUTPUT_FILE="${2:-./.env.local.azure}"

# Get required values from parameter or env var, fail if missing
get_required_value() {
  local param_name="$1"
  local env_var="$2"
  local field_name="$3"
  
  # Check if provided as parameter
  if [ -n "$param_name" ]; then
    echo "$param_name"
    return
  fi
  
  # Check environment variable
  if [ -n "${!env_var:-}" ]; then
    echo "${!env_var}"
    return
  fi
  
  # Fail - no value available
  echo "❌ Missing required configuration: $field_name" >&2
  echo "   Provide via parameter or $env_var environment variable" >&2
  exit 1
}

if [ ! -d "$IAC_DIR" ]; then
  echo "IaC directory not found: $IAC_DIR" >&2
  exit 1
fi

pushd "$IAC_DIR" >/dev/null
JSON=$(terraform output -json || true)
if [ -z "$JSON" ]; then
  echo "Terraform output is empty. Run 'terraform apply' first." >&2
  exit 1
fi

# Extract required outputs
APP_CLIENT_ID=$(echo "$JSON" | python -c "import json,sys; o=json.load(sys.stdin); print(o.get('app_client_id', {}).get('value', ''))")
APP_TENANT_ID=$(echo "$JSON" | python -c "import json,sys; o=json.load(sys.stdin); print(o.get('app_tenant_id', {}).get('value', ''))")
ADMIN_GROUP_ID=$(echo "$JSON" | python -c "import json,sys; o=json.load(sys.stdin); print(o.get('admin_group_id', {}).get('value', ''))")

# Validate required Terraform outputs
if [ -z "$APP_CLIENT_ID" ] || [ -z "$APP_TENANT_ID" ] || [ -z "$ADMIN_GROUP_ID" ]; then
  echo "❌ Missing required Terraform outputs" >&2
  echo "   Ensure 'terraform apply' has been run and outputs include:" >&2
  [ -z "$APP_TENANT_ID" ] && echo "   - app_tenant_id" >&2
  [ -z "$APP_CLIENT_ID" ] && echo "   - app_client_id" >&2
  [ -z "$ADMIN_GROUP_ID" ] && echo "   - admin_group_id" >&2
  exit 1
fi

# Extract optional outputs
KEYVAULT_URL=$(echo "$JSON" | python -c "import json,sys; o=json.load(sys.stdin); print(o.get('key_vault_uri', {}).get('value', ''))" || true)
KEYVAULT_NAME=$(echo "$JSON" | python -c "import json,sys; o=json.load(sys.stdin); print(o.get('key_vault_name', {}).get('value', ''))" || true)
STORAGE_ACCOUNT=$(echo "$JSON" | python -c "import json,sys; o=json.load(sys.stdin); print(o.get('storage_account_name', {}).get('value', ''))" || true)
STORAGE_CONTAINER=$(echo "$JSON" | python -c "import json,sys; o=json.load(sys.stdin); print(o.get('storage_container_name', {}).get('value', ''))" || true)
EVENTGRID_URI=$(echo "$JSON" | python -c "import json,sys; o=json.load(sys.stdin); print(o.get('eventgrid_topic_endpoint', {}).get('value', ''))" || true)
EVENTGRID_KEY=$(echo "$JSON" | python -c "import json,sys; o=json.load(sys.stdin); print(o.get('eventgrid_topic_key', {}).get('value', ''))" || true)
APPINSIGHTS_KEY=$(echo "$JSON" | python -c "import json,sys; o=json.load(sys.stdin); print(o.get('appinsights_instrumentation_key', {}).get('value', ''))" || true)

popd >/dev/null

# Validate required secrets
CLIENT_SECRET=$(get_required_value "${GRAPH_CLIENT_SECRET:-}" "GRAPH_CLIENT_SECRET" "GRAPH_CLIENT_SECRET")
WEBHOOK_SECRET=$(get_required_value "${WEBHOOK_AUTH_SECRET:-}" "WEBHOOK_AUTH_SECRET" "WEBHOOK_AUTH_SECRET")

cat > "$OUTPUT_FILE" <<EOF
# Generated by scripts/generate-azure-env.sh
# Do not commit this file

# Azure Application (from Terraform - validated)
GRAPH_TENANT_ID=$APP_TENANT_ID
GRAPH_CLIENT_ID=$APP_CLIENT_ID
GRAPH_CLIENT_SECRET=$CLIENT_SECRET
ENTRA_GROUP_ID=$ADMIN_GROUP_ID

# Key Vault
AZURE_KEYVAULT_URL=${KEYVAULT_URL:-}
AZURE_KEYVAULT_NAME=${KEYVAULT_NAME:-}

# Storage
AZURE_STORAGE_ACCOUNT=${STORAGE_ACCOUNT:-}
AZURE_STORAGE_CONTAINER=${STORAGE_CONTAINER:-}

# Event Grid
EVENTGRID_URI=${EVENTGRID_URI:-}
EVENTGRID_KEY=${EVENTGRID_KEY:-}

# Application Insights
APPINSIGHTS_INSTRUMENTATION_KEY=${APPINSIGHTS_KEY:-}

# Required secrets (validated at generation time)
WEBHOOK_AUTH_SECRET=$WEBHOOK_SECRET
EOF

echo ""
echo "✅ Generated: $OUTPUT_FILE"
echo "   All required values validated and present"
