param(
  [string]$IaCDir = "./iac/aws",
  [string]$OutputFile = "./.env.local",
  [string]$WebhookSecret = "",
  [string]$TenantId = "",
  [string]$ClientId = "",
  [string]$ClientSecret = "",
  [string]$GroupId = ""
)

function Get-RequiredValue {
  param(
    [string]$Value,
    [string]$EnvVar,
    [string]$FieldName
  )
  
  # 1. Use provided parameter if given
  if ($Value) {
    return $Value
  }
  
  # 2. Check environment variable
  if ($EnvVar -and (Test-Path "env:$EnvVar")) {
    return (Get-Item "env:$EnvVar").Value
  }
  
  # 3. Fail - no value available
  Write-Error "❌ Missing required configuration: $FieldName`n   Provide via -$($FieldName -replace '_', '') parameter or $EnvVar environment variable"
  exit 1
}

$ErrorActionPreference = "Stop"

if (-not (Test-Path $IaCDir)) {
  Write-Error "IaC directory not found: $IaCDir"
  exit 1
}

$originalLocation = Get-Location
try {
  Push-Location $IaCDir
  $json = terraform output -json
  if (-not $json) {
    Write-Error "Terraform output is empty. Run 'terraform apply' first."
    exit 1
  }

  $outputs = $json | ConvertFrom-Json
  $apiUrl = $outputs.api_webhook_url.value
  $bucket = $outputs.s3_bucket_name.value
  $eventGridUri = if ($outputs.eventgrid_topic_endpoint) { $outputs.eventgrid_topic_endpoint.value } else { $null }
  $eventGridKey = if ($outputs.eventgrid_topic_key) { $outputs.eventgrid_topic_key.value } else { $null }

  if (-not $apiUrl -or -not $bucket) {
    Write-Error "❌ Missing required Terraform outputs"
    Write-Error "   Ensure 'terraform apply' has been run and outputs include:"
    Write-Error "   - api_webhook_url"
    Write-Error "   - s3_bucket_name"
    exit 1
  }

  # Get required values - will fail if missing
  $authSecret = Get-RequiredValue -Value $WebhookSecret -EnvVar "WEBHOOK_AUTH_SECRET" -FieldName "WEBHOOK_AUTH_SECRET"
  $tenantId = Get-RequiredValue -Value $TenantId -EnvVar "GRAPH_TENANT_ID" -FieldName "GRAPH_TENANT_ID"
  $clientId = Get-RequiredValue -Value $ClientId -EnvVar "GRAPH_CLIENT_ID" -FieldName "GRAPH_CLIENT_ID"
  $clientSecret = Get-RequiredValue -Value $ClientSecret -EnvVar "GRAPH_CLIENT_SECRET" -FieldName "GRAPH_CLIENT_SECRET"
  $grpId = Get-RequiredValue -Value $GroupId -EnvVar "ENTRA_GROUP_ID" -FieldName "ENTRA_GROUP_ID"

  $content = @(
    "# Generated by scripts/generate-aws-env.ps1",
    "# Do not commit this file",
    "",
    "AWS_WEBHOOK_ENDPOINT=$apiUrl",
    "AWS_S3_BUCKET=$bucket",
    "",
    "# Required values (validated at generation time)",
    "WEBHOOK_AUTH_SECRET=$authSecret",
    "GRAPH_TENANT_ID=$tenantId",
    "GRAPH_CLIENT_ID=$clientId",
    "GRAPH_CLIENT_SECRET=$clientSecret",
    "ENTRA_GROUP_ID=$grpId",
    "",
    "# Optional: Event Grid",
    "EVENTGRID_URI=$(if ($eventGridUri) { $eventGridUri } else { '' })",
    "EVENTGRID_KEY=$(if ($eventGridKey) { $eventGridKey } else { '' })"
  ) -join "`n"

  Pop-Location
  Set-Content -Path $OutputFile -Value $content -Encoding UTF8
  Write-Host ""
  Write-Host "✅ Generated: $OutputFile" -ForegroundColor Green
  Write-Host "   All required values validated and present" -ForegroundColor Green
} finally {
  Pop-Location
}
