param(
  [string]$IaCDir = "./iac/azure",
  [string]$OutputFile = "./.env.local.azure",
  [string]$ClientSecret = "",
  [string]$WebhookSecret = ""
)

function Get-RequiredValue {
  param(
    [string]$Value,
    [string]$EnvVar,
    [string]$FieldName
  )
  
  # 1. Use provided parameter if given
  if ($Value) {
    return $Value
  }
  
  # 2. Check environment variable
  if ($EnvVar -and (Test-Path "env:$EnvVar")) {
    return (Get-Item "env:$EnvVar").Value
  }
  
  # 3. Fail - no value available
  Write-Error "❌ Missing required configuration: $FieldName`n   Provide via -$($FieldName -replace '_', '') parameter or $EnvVar environment variable"
  exit 1
}

$ErrorActionPreference = "Stop"

if (-not (Test-Path $IaCDir)) {
  Write-Error "IaC directory not found: $IaCDir"
  exit 1
}

Push-Location $IaCDir
try {
  $json = terraform output -json
  if (-not $json) {
    Write-Error "Terraform output is empty. Run 'terraform apply' first."
    exit 1
  }

  $outputs = $json | ConvertFrom-Json
  
  # Extract required outputs
  $appClientId = if ($outputs.app_client_id) { $outputs.app_client_id.value } else { $null }
  $appTenantId = if ($outputs.app_tenant_id) { $outputs.app_tenant_id.value } else { $null }
  $adminGroupId = if ($outputs.admin_group_id) { $outputs.admin_group_id.value } else { $null }
  
  # Validate required Terraform outputs
  if (-not $appClientId -or -not $appTenantId -or -not $adminGroupId) {
    Write-Error "❌ Missing required Terraform outputs"
    Write-Error "   Ensure 'terraform apply' has been run and outputs include:"
    if (-not $appTenantId) { Write-Error "   - app_tenant_id" }
    if (-not $appClientId) { Write-Error "   - app_client_id" }
    if (-not $adminGroupId) { Write-Error "   - admin_group_id" }
    exit 1
  }
  
  # Extract optional outputs
  $kvUri = if ($outputs.key_vault_uri) { $outputs.key_vault_uri.value } else { $null }
  $kvName = if ($outputs.key_vault_name) { $outputs.key_vault_name.value } else { $null }
  $storageAccount = if ($outputs.storage_account_name) { $outputs.storage_account_name.value } else { $null }
  $storageContainer = if ($outputs.storage_container_name) { $outputs.storage_container_name.value } else { $null }
  $eventGridUri = if ($outputs.eventgrid_topic_endpoint) { $outputs.eventgrid_topic_endpoint.value } else { $null }
  $eventGridKey = if ($outputs.eventgrid_topic_key) { $outputs.eventgrid_topic_key.value } else { $null }
  $appInsightsKey = if ($outputs.appinsights_instrumentation_key) { $outputs.appinsights_instrumentation_key.value } else { $null }

  # Get required secrets from parameters or env vars - will fail if missing
  $secret = Get-RequiredValue -Value $ClientSecret -EnvVar "GRAPH_CLIENT_SECRET" -FieldName "GRAPH_CLIENT_SECRET"
  $authSecret = Get-RequiredValue -Value $WebhookSecret -EnvVar "WEBHOOK_AUTH_SECRET" -FieldName "WEBHOOK_AUTH_SECRET"

  $content = @(
    "# Generated by scripts/generate-azure-env.ps1",
    "# Do not commit this file",
    "",
    "# Azure Application (from Terraform - validated)",
    "GRAPH_TENANT_ID=$appTenantId",
    "GRAPH_CLIENT_ID=$appClientId",
    "GRAPH_CLIENT_SECRET=$secret",
    "ENTRA_GROUP_ID=$adminGroupId",
    "",
    "# Key Vault",
    "AZURE_KEYVAULT_URL=$(if ($kvUri) { $kvUri } else { '' })",
    "AZURE_KEYVAULT_NAME=$(if ($kvName) { $kvName } else { '' })",
    "",
    "# Storage",
    "AZURE_STORAGE_ACCOUNT=$(if ($storageAccount) { $storageAccount } else { '' })",
    "AZURE_STORAGE_CONTAINER=$(if ($storageContainer) { $storageContainer } else { '' })",
    "",
    "# Event Grid",
    "EVENTGRID_URI=$(if ($eventGridUri) { $eventGridUri } else { '' })",
    "EVENTGRID_KEY=$(if ($eventGridKey) { $eventGridKey } else { '' })",
    "",
    "# Application Insights",
    "APPINSIGHTS_INSTRUMENTATION_KEY=$(if ($appInsightsKey) { $appInsightsKey } else { '' })",
    "",
    "# Required secrets (validated at generation time)",
    "WEBHOOK_AUTH_SECRET=$authSecret"
  ) -join "`n"

  Pop-Location
  Set-Content -Path $OutputFile -Value $content -Encoding UTF8
  Write-Host ""
  Write-Host "✅ Generated: $OutputFile" -ForegroundColor Green
  Write-Host "   All required values validated and present" -ForegroundColor Green
} finally {
  if ((Get-Location).Path -eq (Resolve-Path $IaCDir).Path) {
    Pop-Location
  }
}
