param(
  [string]$IaCDir = "./iac/aws",
  [string]$OutputFile = "./.env.local",
  [string]$WebhookSecret = "",
  [string]$TenantId = "",
  [string]$ClientId = "",
  [string]$ClientSecret = "",
  [string]$GroupId = ""
)

function Get-ValueOrDefault {
  param(
    [string]$Value,
    [string]$EnvVar,
    [string]$Prompt
  )
  
  # 1. Use provided parameter if given
  if ($Value) {
    return $Value
  }
  
  # 2. Check environment variable
  if ($EnvVar -and (Test-Path "env:$EnvVar")) {
    return (Get-Item "env:$EnvVar").Value
  }
  
  # 3. Return placeholder
  return "<REPLACE_ME>"
}

$ErrorActionPreference = "Stop"

if (-not (Test-Path $IaCDir)) {
  Write-Error "IaC directory not found: $IaCDir"
  exit 1
}

$originalLocation = Get-Location
try {
  Push-Location $IaCDir
  $json = terraform output -json
  if (-not $json) {
    Write-Error "Terraform output is empty. Run 'terraform apply' first."
    exit 1
  }

  $outputs = $json | ConvertFrom-Json
  $apiUrl = $outputs.api_webhook_url.value
  $bucket = $outputs.s3_bucket_name.value
  $eventGridUri = if ($outputs.eventgrid_topic_endpoint) { $outputs.eventgrid_topic_endpoint.value } else { $null }
  $eventGridKey = if ($outputs.eventgrid_topic_key) { $outputs.eventgrid_topic_key.value } else { $null }

  if (-not $apiUrl -or -not $bucket) {
    Write-Error "Missing expected outputs. Ensure api_webhook_url and s3_bucket_name are defined."
    exit 1
  }

  # Get values from parameters, env vars, or use placeholders
  $authSecret = Get-ValueOrDefault -Value $WebhookSecret -EnvVar "WEBHOOK_AUTH_SECRET"
  $tenantId = Get-ValueOrDefault -Value $TenantId -EnvVar "GRAPH_TENANT_ID"
  $clientId = Get-ValueOrDefault -Value $ClientId -EnvVar "GRAPH_CLIENT_ID"
  $clientSecret = Get-ValueOrDefault -Value $ClientSecret -EnvVar "GRAPH_CLIENT_SECRET"
  $grpId = Get-ValueOrDefault -Value $GroupId -EnvVar "ENTRA_GROUP_ID"

  $content = @(
    "# Generated by scripts/generate-aws-env.ps1",
    "# Do not commit this file",
    "",
    "AWS_WEBHOOK_ENDPOINT=$apiUrl",
    "AWS_S3_BUCKET=$bucket",
    "",
    "# Required secrets (from parameters, env vars, or <REPLACE_ME>)",
    "WEBHOOK_AUTH_SECRET=$authSecret",
    "GRAPH_TENANT_ID=$tenantId",
    "GRAPH_CLIENT_ID=$clientId",
    "GRAPH_CLIENT_SECRET=$clientSecret",
    "ENTRA_GROUP_ID=$grpId",
    "",
    "# Optional: Event Grid",
    "EVENTGRID_URI=$(if ($eventGridUri) { $eventGridUri } else { '<REPLACE_ME>' })",
    "EVENTGRID_KEY=$(if ($eventGridKey) { $eventGridKey } else { '<REPLACE_ME>' })"
  ) -join "`n"

  Pop-Location
  Set-Content -Path $OutputFile -Value $content -Encoding UTF8
  Write-Host "✅ Generated: $OutputFile"
  Write-Host "   - Values from Terraform outputs"
  Write-Host "   - Secrets from parameters/env vars"
  Write-Host "   - Remaining <REPLACE_ME> values need manual configuration"
} finally {
  Pop-Location
}
